name: Integration Test

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'benchmark/**'
      - 'docs/**'
      - 'examples/**'
      - '*.md'

  pull_request:
    branches:
      - master
    paths-ignore:
      - 'benchmark/**'
      - 'docs/**'
      - 'examples/**'
      - '*.md'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    #- name: Run unit tests
    #  run: npm run test:unit

    - name: Start containers
      run: docker-compose up -d
      working-directory: ./test

    - name: Sleeping 30 secs
      run: sleep 30

    - name: Check containers
      run: docker-compose ps
      working-directory: ./test

    - name: Check logs
      run: docker-compose logs
      working-directory: ./test

    - name: Run tests
      run: npm test
      timeout-minutes: 15
      env:
        GITHUB_ACTIONS_CI: true

    # - name: Run leak detection tests
    #   run: npm run test:leak
    #   env:
    #     GITHUB_ACTIONS_CI: true

    - name: Show container logs (in case of failure)
      run: docker-compose logs
      if: failure()
      working-directory: ./test

    - name: Stop containers
      run: docker-compose down -v
      working-directory: ./test

    - name: Upload code coverage
      run: npm run coverall
      if: success() && github.ref == 'refs/heads/master'
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
